import cron from 'node-cron';
import axios from 'axios';
// Adjust model imports based on your actual database schema names
import UserProfile from '../models/UserProfile.model.js'; 
import NotificationLog from '../models/NotificationLog.model.js'; 

/**
 * Helper to extract owner and repo name from a GitHub URL
 */
const parseGithubUrl = (url) => {
  const match = url.match(/github\.com\/([^/]+)\/([^/]+)/);
  return match ? { owner: match[1], repo: match[2].replace('.git', '') } : null;
};

/**
 * Sync logic for GitHub repositories
 */
export const syncGithubProjects = async () => {
  try {
    // Find all UserProfiles that have projects linked to GitHub
    const userProfiles = await UserProfile.find({ 
      'projects.githubRepoUrl': { $exists: true, $ne: null } 
    });

    console.log(`[GitHub Sync] Starting daily portfolio sync. Processing ${userProfiles.length} profiles.`);

    let totalSynced = 0;
    let totalSkipped = 0;

    for (const profile of userProfiles) {
      let hasUpdates = false;
      let updatedProjectsCount = 0;

      for (const project of profile.projects) {
        if (!project.githubRepoUrl) continue;

        const repoInfo = parseGithubUrl(project.githubRepoUrl);
        if (!repoInfo) continue;

        try {
          // Fetch latest repo data from GitHub
          const { data: repoData } = await axios.get(`https://api.github.com/repos/${repoInfo.owner}/${repoInfo.repo}`, {
            headers: process.env.GITHUB_TOKEN ? { Authorization: `token ${process.env.GITHUB_TOKEN}` } : {}
          });

          const repoUpdatedAt = new Date(repoData.updated_at);
          const lastSyncedAt = project.lastSyncedAt ? new Date(project.lastSyncedAt) : new Date(0);

          // Only proceed if the GitHub repo has been updated since our last sync
          if (repoUpdatedAt > lastSyncedAt) {
            
            // REQUIREMENT: Do NOT overwrite user's custom content.
            // We only update if the user hasn't flagged it as manually edited, 
            // OR we store it in designated "draft/autoGenerated" fields.
            if (!project.isManuallyEdited) {
              if (!project.autoData) project.autoData = {};
              
              // Update auto-generated fields (draft data)
              project.autoData.description = repoData.description || project.autoData.description;
              
              // Attempt to fetch README for deeper content
              try {
                const { data: readmeData } = await axios.get(`https://api.github.com/repos/${repoInfo.owner}/${repoInfo.repo}/readme`, {
                   headers: process.env.GITHUB_TOKEN ? { Authorization: `token ${process.env.GITHUB_TOKEN}` } : {}
                });
                project.autoData.readme = Buffer.from(readmeData.content, 'base64').toString('utf-8');
              } catch (readmeErr) {
                // Ignore if no README exists
              }

              project.lastSyncedAt = new Date();
              hasUpdates = true;
              updatedProjectsCount++;
            }
          }
        } catch (err) {
          console.error(`[GitHub Sync] Failed to fetch data for ${project.githubRepoUrl} (Profile: ${profile._id}, User: ${profile.uid}): ${err.message}`);
        }
      }

      // REQUIREMENT: Notify user of updates via in-app notification
      // REQUIREMENT: Do NOT re-deploy automatically (just save to DB)
      if (hasUpdates) {
        await profile.save();

        await NotificationLog.create({
          userId: profile.uid,
          type: 'PORTFOLIO_SYNC',
          title: 'GitHub Projects Synced',
          message: `We found updates in ${updatedProjectsCount} of your linked GitHub repositories. We've updated your draft data!`,
          read: false,
          createdAt: new Date()
        });
        totalSynced++;
        console.log(`[GitHub Sync] Synced profile ${profile._id} (User: ${profile.uid}). Updated ${updatedProjectsCount} projects.`);
      } else {
        totalSkipped++;
        console.log(`[GitHub Sync] Skipped profile ${profile._id} (User: ${profile.uid}) - no new repository changes detected.`);
      }
    }
    
    console.log(`[GitHub Sync] Daily sync completed. Synced: ${totalSynced}, Skipped: ${totalSkipped}`);
  } catch (error) {
    console.error('[GitHub Sync] Fatal error during sync:', error);
  }
};

/**
 * Initialize Cron Job to run daily at Midnight
 */
export const initGitHubSyncCron = () => {
  cron.schedule('0 0 * * *', () => {
    syncGithubProjects();
  });
  console.log('🕒 GitHub Portfolio Sync Cron Job Initialized (Runs daily at 00:00)');
};